### PR TITLE
start: Ignore e-mail failure

### LINKED ISSUE #67: If email fails to send startup mail it goes into restart loop
Failing to send email at startup should not prevent it from starting up.

### PR DESCRIPTION
**Pull request by jonaski**
Fixes #67

### CODE REVIEW

**Review by ralftar — COMMENTED** [review]
Does it log (STDOUT) that it failed to send?

File: scripts/start.sh [hunk 1]
```diff
@@ -339,9 +339,9 @@ mail_body="${mail_body}
 Vendanor CloudDump v${VERSION}"
 
 if [ "${MAIL}" = "mutt" ]; then
-  echo "${mail_body}" | EMAIL="${MAILFROM} <${MAILFROM}>" ${MAIL} -s "[Started] CloudDump ${HOST}" "${MAILTO}" || exit 1
+  echo "${mail_body}" | EMAIL="${MAILFROM} <${MAILFROM}>" ${MAIL} -s "[Started] CloudDump ${HOST}" "${MAILTO}"
 else
-  echo "${mail_body}" | ${MAIL} -r "${MAILFROM} <${MAILFROM}>" -s "[Started] CloudDump ${HOST}" "${MAILTO}" || exit 1
+  echo "${mail_body}" | ${MAIL} -r "${MAILFROM} <${MAILFROM}>" -s "[Started] CloudDump ${HOST}" "${MAILTO}"
 fi
```
Comment (ralftar) [inline scripts/start.sh:345]:
```suggestion
if [ "${MAIL}" = "mutt" ]; then
  if ! echo "${mail_body}" | EMAIL="${MAILFROM} <${MAILFROM}>" ${MAIL} -s "[Started] CloudDump ${HOST}" "${MAILTO}"; then
    error "Failed to send startup email to ${MAILTO} using mutt."
  fi
else
  if ! echo "${mail_body}" | ${MAIL} -r "${MAILFROM} <${MAILFROM}>" -s "[Started] CloudDump ${HOST}" "${MAILTO}"; then
    error "Failed to send startup email to ${MAILTO} using ${MAIL}."
  fi
fi
```
